version: '2'
services:
  frontend:
    image: kammana/emp-fe-comp:1.0
    container_name: emp-frontend-layer
    ports:
     - "4200:4200"
    networks:
      - abhijeet-app
  mongodb:
    container_name: mongodb-layer
    image: "mongo:latest"
    networks:
      - abhijeet-app
    volumes:
      - mongodb:/data/db
  emp-api:
    container_name: emp-api-layer
    image: kammana/boot-api:5.0
    ports:
     - "8080:8080"
    networks:
      - abhijeet-app
volumes:
  mongodb:
networks:
  abhijeet-app:
    driver: bridge
